server:
  port: 8800
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  application:
    name: api_gateway_server
  cloud:
    gateway:
      discovery:
        locator:
          # 开启微服务名称自动转发
          enabled: true
          # 微服务名称以小写显示
          lower-case-service-id: true
      routes:
        #配置路由：路由id、断言、
        - id: product-server
          #          uri: http://127.0.0.1:9001
          #根据微服务名称从注册中心获取请求地址
          uri: lb://product-server
          # 断言（判断条件）
          predicates:
            - Path=/product/**
          # 路由过滤规则
          filters:
  #            - name: RequestRateLimiter
  #              args:
  #                # 使用SpEl从容器中获取对象
  #                key-resolver: '#{@IpKeyResolver}'
  #                # 令牌桶每秒填充平均速率
  #                # 令牌桶的上限
  #                redis-rate-limiter.replenishRate: 1
  #                redis-rate-limiter.burstCapacity: 3
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    sender:
      type: web #数据传输方式
  sleuth:
    sampler:
      probability: 1 #采样比

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9800/eureka,http://localhost:8000/eureka


logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug


