server:
  port: 9002
spring:
  application:
    name: product-server
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    sender:
      type: web #数据传输方式
  sleuth:
    sampler:
      probability: 1 #采样比
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        enabled: true
#        register: true
#        instance-id: ${spring.application.name}
#        service-name: ${spring.application.name}
#        port: ${server.port}
#        prefer-ip-address: true
#        ip-address: ${spring.cloud.client.ip-address}
#eureka配置
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:9800/eureka,http://localhost:8000/eureka
#设置服务的负载均衡策略
#order-server:
#  ribbon:
#feign配置
feign:
  hystrix:
    enabled: true
  client:
    config:
      order-server:
        #日志等级 NONE BASIC FULL
        loggerlevel: FULL
logging:
  level:
    com.zwl.feign.OrderServerClient: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
#hystrix配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
