server:
  port: 7002
spring:
  application:
    name: stream_producer
  cloud:
    stream:
      rocketmq:
        default:
          producer:
            vipChannelEnabled: false
        binder:
          name-server: 192.168.31.25:9876
      bindings:
        output:
          group: groupA
          destination: mytopic