server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9800/eureka,http://localhost:8000/eureka
  instance:
    #使用ip地址注册
    prefer-ip-address: true
    #发送心跳间隔时间
    lease-renewal-interval-in-seconds: 5
    #续约到期时间
    lease-expiration-duration-in-seconds: 10
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
spring:
  application:
    name: order-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    sender:
      type: web #数据传输方式
  sleuth:
    sampler:
      probability: 1 #采样比
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        enabled: true
#        register: true
#        instance-id: ${spring.application.name}
#        service-name: ${spring.application.name}
#        port: ${server.port}
#        prefer-ip-address: true
#        ip-address: ${spring.cloud.client.ip-address}