server:
  port: 9801
spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhao_weilong/config.git

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9800/eureka,http://localhost:8000/eureka
  instance:
    #使用ip地址注册
    prefer-ip-address: true
    #发送心跳间隔时间
    lease-renewal-interval-in-seconds: 5
    #续约到期时间
    lease-expiration-duration-in-seconds: 10
    instance-id: ${spring.cloud.client.ip-address}:${server.port}